<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
    <testsuite name="LuaUnit" id="00001" package="" hostname="localhost" tests="7" timestamp="2016-01-30T22:33:12" time="0.015" errors="2" failures="4">
        <properties>
            <property name="Lua Version" value="Lua 5.2"/>
            <property name="LuaUnit Version" value="3.2"/>
        </properties>
        <testcase classname="TestToto" name="TestToto.test3" time="0.000">
        </testcase>
        <testcase classname="TestToto" name="TestToto.test4" time="0.000">
            <failure type="example_with_luaunit.lua:43: Received the not expected value: 1">
                <![CDATA[stack traceback:
	example_with_luaunit.lua:43: in function 'TestToto.test4']]></failure>
        </testcase>
        <testcase classname="TestToto" name="TestToto.test5" time="0.000">
            <failure type="example_with_luaunit.lua:49: expected: false, actual: 1">
                <![CDATA[stack traceback:
	example_with_luaunit.lua:49: in function 'TestToto.test5']]></failure>
        </testcase>
        <testcase classname="TestToto" name="TestToto.test6" time="0.000">
            <failure type="example_with_luaunit.lua:54: expected: true, actual: false">
                <![CDATA[stack traceback:
	example_with_luaunit.lua:54: in function 'TestToto.test6']]></failure>
        </testcase>
        <testcase classname="TestToto" name="TestToto.test7" time="0.000">
            <failure type="example_with_luaunit.lua:60: expected: {1, 2, three=3}
actual: {1, 2}">
                <![CDATA[stack traceback:
	example_with_luaunit.lua:60: in function 'TestToto.test7']]></failure>
        </testcase>
        <testcase classname="TestToto" name="TestToto.test8a" time="0.000">
            <error type="example_with_luaunit.lua:78: Bouhouhoum error!">
                <![CDATA[stack traceback:
	example_with_luaunit.lua:78: in function 'funcWithError'
	example_with_luaunit.lua:65: in function 'TestToto.test8a']]></error>
        </testcase>
        <testcase classname="TestToto" name="TestToto.test8b" time="0.000">
            <error type="example_with_luaunit.lua:78: Bouhouhoum error!">
                <![CDATA[stack traceback:
	example_with_luaunit.lua:78: in function 'funcWithError'
	example_with_luaunit.lua:74: in function 'funcWithFuncWithError'
	example_with_luaunit.lua:70: in function 'TestToto.test8b']]></error>
        </testcase>
    <system-out/>
    <system-err/>
    </testsuite>
</testsuites>
